version: 2
updates:
  # master
  - package-ecosystem: "pip"
    directory: "/dev_requirements"
    schedule:
      interval: "daily"

  # mainline-1.x
  - package-ecosystem: "pip"
    directory: "/dev_requirements"
    schedule:
      interval: "daily"
    target-branch: "mainline-1.x"

  # mainline-2.x
  - package-ecosystem: "pip"
    directory: "/dev_requirements"
    schedule:
      interval: "daily"
    target-branch: "mainline-2.x"

  # Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"