version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: py37_integ
      buildspec: codebuild/py37/integ.yml
    - identifier: py37_examples
      buildspec: codebuild/py37/examples.yml
    - identifier: py37_awses_local
      buildspec: codebuild/py37/awses_local.yml

    - identifier: py38_integ
      buildspec: codebuild/py38/integ.yml
    - identifier: py38_examples
      buildspec: codebuild/py38/examples.yml
    - identifier: py38_awses_local
      buildspec: codebuild/py38/awses_local.yml

    - identifier: py39_integ
      buildspec: codebuild/py39/integ.yml
    - identifier: py39_examples
      buildspec: codebuild/py39/examples.yml
    - identifier: py39_awses_latest

    - identifier: py310_integ
      buildspec: codebuild/py310/integ.yml
    - identifier: py310_examples
      buildspec: codebuild/py310/examples.yml
    - identifier: py310_awses_latest
      buildspec: codebuild/py310/awses_local.yml


    - identifier: code_coverage
      buildspec: codebuild/coverage/coverage.yml

    - identifier: compliance
      buildspec: codebuild/compliance/compliance.yml
