version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: py35_integ
      buildspec: codebuild/py35/integ.yml
    - identifier: py35_examples
      buildspec: codebuild/py35/examples.yml
    - identifier: py35_awses_local
      buildspec: codebuild/py35/awses_local.yml

    - identifier: py36_integ
      buildspec: codebuild/py36/integ.yml
    - identifier: py36_examples
      buildspec: codebuild/py36/examples.yml
    - identifier: py36_awses_local
      buildspec: codebuild/py36/awses_local.yml

    - identifier: py37_integ
      buildspec: codebuild/py37/integ.yml
    - identifier: py37_examples
      buildspec: codebuild/py37/examples.yml
    - identifier: py37_awses_local
      buildspec: codebuild/py37/awses_local.yml

    - identifier: py38_integ
      buildspec: codebuild/py38/integ.yml
    - identifier: py38_examples
      buildspec: codebuild/py38/examples.yml
    - identifier: py38_awses_local
      buildspec: codebuild/py38/awses_local.yml

    - identifier: py39_integ
      buildspec: codebuild/py39/integ.yml
    - identifier: py39_examples
      buildspec: codebuild/py39/examples.yml
    - identifier: py39_awses_latest

    - identifier: code_coverage
      buildspec: codebuild/coverage/coverage.yml

    - identifier: compliance
      buildspec: codebuild/compliance/compliance.yml
