version: 0.2

batch:
  fast-fail: false
  build-graph:

    # 3.8
    - identifier: py38_integ
      buildspec: codebuild/py38/integ.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py38_examples
      buildspec: codebuild/py38/examples.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py38_decrypt_dafny_esdk_vectors
      buildspec: codebuild/py38/decrypt_dafny_esdk_vectors.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py38_decrypt_net_401_vectors
      buildspec: codebuild/py38/decrypt_net_401_vectors.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py38_encrypt_masterkey
      buildspec: codebuild/py38/encrypt_masterkey.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py38_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py38/generate_decrypt_vectors_masterkey.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py38_decrypt_masterkey_with_masterkey
      depend-on: 
       - py38_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py38/decrypt_masterkey_with_masterkey.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py38_decrypt_masterkey_with_js
      depend-on: 
       - py38_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py38/decrypt_masterkey_with_js.yml
      env:
        image: aws/codebuild/standard:5.0

    # 3.9
    - identifier: py39_integ
      buildspec: codebuild/py39/integ.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py39_examples
      buildspec: codebuild/py39/examples.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py39_decrypt_dafny_esdk_vectors
      buildspec: codebuild/py39/decrypt_dafny_esdk_vectors.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py39_decrypt_net_401_vectors
      buildspec: codebuild/py39/decrypt_net_401_vectors.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py39_encrypt_masterkey
      buildspec: codebuild/py39/encrypt_masterkey.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py39_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py39/generate_decrypt_vectors_masterkey.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py39_decrypt_masterkey_with_masterkey
      depend-on: 
       - py39_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py39/decrypt_masterkey_with_masterkey.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py39_decrypt_masterkey_with_js
      depend-on: 
       - py39_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py39/decrypt_masterkey_with_js.yml
      env:
        image: aws/codebuild/standard:5.0

    # 3.10
    - identifier: py310_integ
      buildspec: codebuild/py310/integ.yml
      env:
        image: aws/codebuild/standard:6.0
    - identifier: py310_examples
      buildspec: codebuild/py310/examples.yml
      env:
        image: aws/codebuild/standard:6.0
    - identifier: py310_decrypt_dafny_esdk_vectors
      buildspec: codebuild/py310/decrypt_dafny_esdk_vectors.yml
      env:
        image: aws/codebuild/standard:6.0
    - identifier: py310_decrypt_net_401_vectors
      buildspec: codebuild/py310/decrypt_net_401_vectors.yml
      env:
        image: aws/codebuild/standard:6.0
    - identifier: py310_encrypt_masterkey
      buildspec: codebuild/py310/encrypt_masterkey.yml
      env:
        image: aws/codebuild/standard:6.0
    - identifier: py310_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py310/generate_decrypt_vectors_masterkey.yml
      env:
        image: aws/codebuild/standard:6.0
    - identifier: py310_decrypt_masterkey_with_masterkey
      depend-on: 
       - py310_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py310/decrypt_masterkey_with_masterkey.yml
      env:
        image: aws/codebuild/standard:6.0
    - identifier: py310_decrypt_masterkey_with_js
      depend-on: 
       - py310_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py310/decrypt_masterkey_with_js.yml
      env:
        image: aws/codebuild/standard:6.0

    - identifier: py311_integ
      buildspec: codebuild/py311/integ.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_integ_mpl
      buildspec: codebuild/py311/integ_mpl.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_performance_tests_mpl
      buildspec: codebuild/py311/performance_tests_mpl.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_examples
      buildspec: codebuild/py311/examples.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_examples_mpl
      buildspec: codebuild/py311/examples_mpl.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_dafny_esdk_vectors_masterkey
      buildspec: codebuild/py311/decrypt_dafny_esdk_vectors_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_dafny_esdk_vectors_keyrings
      buildspec: codebuild/py311/decrypt_dafny_esdk_vectors_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_net_401_vectors_masterkey
      buildspec: codebuild/py311/decrypt_net_401_vectors_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_net_401_vectors_keyrings
      buildspec: codebuild/py311/decrypt_net_401_vectors_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_encrypt_masterkey
      buildspec: codebuild/py311/encrypt_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_encrypt_keyrings
      buildspec: codebuild/py311/encrypt_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py311/generate_decrypt_vectors_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_masterkey_with_masterkey
      depend-on: 
       - py311_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py311/decrypt_masterkey_with_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_masterkey_with_keyrings
      depend-on: 
       - py311_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py311/decrypt_masterkey_with_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_masterkey_with_js
      depend-on: 
       - py311_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py311/decrypt_masterkey_with_js.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_generate_decrypt_vectors_keyrings
      buildspec: codebuild/py311/generate_decrypt_vectors_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_keyrings_with_masterkey
      depend-on: 
       - py311_generate_decrypt_vectors_keyrings
      buildspec: codebuild/py311/decrypt_keyrings_with_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_keyrings_with_keyrings
      depend-on: 
       - py311_generate_decrypt_vectors_keyrings
      buildspec: codebuild/py311/decrypt_keyrings_with_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_keyrings_with_js
      depend-on: 
       - py311_generate_decrypt_vectors_keyrings
      buildspec: codebuild/py311/decrypt_keyrings_with_js.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_golden_manifest_with_keyrings
      buildspec: codebuild/py311/decrypt_golden_manifest_with_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_golden_manifest_with_masterkey
      buildspec: codebuild/py311/decrypt_golden_manifest_with_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    

    - identifier: py312_integ
      buildspec: codebuild/py312/integ.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_integ_mpl
      buildspec: codebuild/py312/integ_mpl.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_performance_tests_mpl
      buildspec: codebuild/py312/performance_tests_mpl.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_examples
      buildspec: codebuild/py312/examples.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_examples_mpl
      buildspec: codebuild/py312/examples_mpl.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_dafny_esdk_vectors_masterkey
      buildspec: codebuild/py312/decrypt_dafny_esdk_vectors_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_dafny_esdk_vectors_keyrings
      buildspec: codebuild/py312/decrypt_dafny_esdk_vectors_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_net_401_vectors_masterkey
      buildspec: codebuild/py312/decrypt_net_401_vectors_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_net_401_vectors_keyrings
      buildspec: codebuild/py312/decrypt_net_401_vectors_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_encrypt_masterkey
      buildspec: codebuild/py312/encrypt_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_encrypt_keyrings
      buildspec: codebuild/py312/encrypt_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py312/generate_decrypt_vectors_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_masterkey_with_masterkey
      depend-on: 
       - py312_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py312/decrypt_masterkey_with_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_masterkey_with_keyrings
      depend-on: 
       - py312_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py312/decrypt_masterkey_with_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_masterkey_with_js
      depend-on: 
       - py312_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py312/decrypt_masterkey_with_js.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_generate_decrypt_vectors_keyrings
      buildspec: codebuild/py312/generate_decrypt_vectors_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_keyrings_with_masterkey
      depend-on: 
       - py312_generate_decrypt_vectors_keyrings
      buildspec: codebuild/py312/decrypt_keyrings_with_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_keyrings_with_keyrings
      depend-on: 
       - py312_generate_decrypt_vectors_keyrings
      buildspec: codebuild/py312/decrypt_keyrings_with_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_keyrings_with_js
      depend-on: 
       - py312_generate_decrypt_vectors_keyrings
      buildspec: codebuild/py312/decrypt_keyrings_with_js.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_generate_hkeyring_decrypt_vectors
      buildspec: codebuild/py312/generate_hkeyring_decrypt_vectors.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_hkeyring_with_masterkey
      depend-on: 
       - py312_generate_hkeyring_decrypt_vectors
      buildspec: codebuild/py312/decrypt_hkeyring_with_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_hkeyring_with_keyrings
      depend-on: 
       - py312_generate_hkeyring_decrypt_vectors
      buildspec: codebuild/py312/decrypt_hkeyring_with_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_hkeyring_with_net
      depend-on: 
       - py312_generate_hkeyring_decrypt_vectors
      buildspec: codebuild/py312/decrypt_hkeyring_with_net.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_golden_manifest_with_keyrings
      buildspec: codebuild/py312/decrypt_golden_manifest_with_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py312_decrypt_golden_manifest_with_masterkey
      buildspec: codebuild/py312/decrypt_golden_manifest_with_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    
    - identifier: code_coverage
      buildspec: codebuild/coverage/coverage.yml
    - identifier: code_coverage_mpl
      buildspec: codebuild/coverage/coverage_mpl.yml
      env:
        image: aws/codebuild/standard:7.0

    - identifier: compliance
      buildspec: codebuild/compliance/compliance.yml
