version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: py37_integ
      buildspec: codebuild/py37/integ.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py37_examples
      buildspec: codebuild/py37/examples.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py37_awses_local
      buildspec: codebuild/py37/awses_local.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py37_decrypt_dafny_esdk_vectors
      buildspec: codebuild/py37/decrypt_dafny_esdk_vectors.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py37_decrypt_net_401_vectors
      buildspec: codebuild/py37/decrypt_net_401_vectors.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py37_generate_decrypt_vectors
      buildspec: codebuild/py37/generate_decrypt_vectors.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py37_decrypt_masterkey_with_masterkey
      depend-on: 
       - py37_generate_decrypt_vectors
      buildspec: codebuild/py37/decrypt_masterkey_with_masterkey.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: py37_decrypt_masterkey_with_js
      depend-on: 
       - py37_generate_decrypt_vectors
      buildspec: codebuild/py37/decrypt_masterkey_with_js.yml
      env:
        image: aws/codebuild/standard:5.0

    # - identifier: py38_integ
    #   buildspec: codebuild/py38/integ.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py38_examples
    #   buildspec: codebuild/py38/examples.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py38_awses_local
    #   buildspec: codebuild/py38/awses_local.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py38_decrypt_dafny_esdk_vectors
    #   buildspec: codebuild/py38/decrypt_dafny_esdk_vectors.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py38_decrypt_net_401_vectors
    #   buildspec: codebuild/py38/decrypt_net_401_vectors.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py38_generate_decrypt_vectors
    #   buildspec: codebuild/py38/generate_decrypt_vectors.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py38_decrypt_masterkey_with_masterkey
    #   depend-on: 
    #    - py38_generate_decrypt_vectors
    #   buildspec: codebuild/py38/decrypt_masterkey_with_masterkey.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py38_decrypt_masterkey_with_js
    #   depend-on: 
    #    - py38_generate_decrypt_vectors
    #   buildspec: codebuild/py38/decrypt_generated_with_js.yml
    #   env:
    #     image: aws/codebuild/standard:5.0

    # - identifier: py39_integ
    #   buildspec: codebuild/py39/integ.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py39_examples
    #   buildspec: codebuild/py39/examples.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py39_awses_latest
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py39_decrypt_dafny_esdk_vectors
    #   buildspec: codebuild/py39/decrypt_dafny_esdk_vectors.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py39_decrypt_net_401_vectors
    #   buildspec: codebuild/py39/decrypt_net_401_vectors.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py39_generate_decrypt_vectors
    #   buildspec: codebuild/py39/generate_decrypt_vectors.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py39_decrypt_masterkey_with_masterkey
    #   depend-on: 
    #    - py39_generate_decrypt_vectors
    #   buildspec: codebuild/py39/decrypt_masterkey_with_masterkey.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py39_decrypt_masterkey_with_js
    #   depend-on: 
    #    - py39_generate_decrypt_vectors
    #   buildspec: codebuild/py39/decrypt_generated_with_js.yml
    #   env:
    #     image: aws/codebuild/standard:5.0

    # - identifier: py310_integ
    #   buildspec: codebuild/py310/integ.yml
    #   env:
    #     image: aws/codebuild/standard:6.0
    # - identifier: py310_examples
    #   buildspec: codebuild/py310/examples.yml
    #   env:
    #     image: aws/codebuild/standard:6.0
    # - identifier: py310_awses_latest
    #   buildspec: codebuild/py310/awses_local.yml
    #   env:
    #     image: aws/codebuild/standard:6.0
    # - identifier: py310_decrypt_dafny_esdk_vectors
    #   buildspec: codebuild/py310/decrypt_dafny_esdk_vectors.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py310_decrypt_net_401_vectors
    #   buildspec: codebuild/py310/decrypt_net_401_vectors.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py310_generate_decrypt_vectors
    #   buildspec: codebuild/py310/generate_decrypt_vectors.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py310_decrypt_masterkey_with_masterkey
    #   depend-on: 
    #    - py310_generate_decrypt_vectors
    #   buildspec: codebuild/py310/decrypt_masterkey_with_masterkey.yml
    #   env:
    #     image: aws/codebuild/standard:5.0
    # - identifier: py310_decrypt_masterkey_with_js
    #   depend-on: 
    #    - py310_generate_decrypt_vectors
    #   buildspec: codebuild/py310/decrypt_generated_with_js.yml
    #   env:
    #     image: aws/codebuild/standard:5.0

    - identifier: py311_integ
      buildspec: codebuild/py311/integ.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_integ_mpl
      buildspec: codebuild/py311/integ_mpl.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_examples
      buildspec: codebuild/py311/examples.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_examples_mpl
      buildspec: codebuild/py311/examples_mpl.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_awses_latest
      buildspec: codebuild/py311/awses_local.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_awses_latest_mpl
      buildspec: codebuild/py311/awses_local_mpl.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_mplawses_latest_mpl
      buildspec: codebuild/py311/mplawses_local_mpl.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_dafny_esdk_vectors_masterkey
      buildspec: codebuild/py311/decrypt_dafny_esdk_vectors_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_dafny_esdk_vectors_keyrings
      buildspec: codebuild/py311/decrypt_dafny_esdk_vectors_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_net_401_vectors_masterkey
      buildspec: codebuild/py311/decrypt_net_401_vectors_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_net_401_vectors_keyrings
      buildspec: codebuild/py311/decrypt_net_401_vectors_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py311/generate_decrypt_vectors_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_masterkey_with_masterkey
      depend-on: 
       - py311_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py311/decrypt_masterkey_with_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_masterkey_with_keyrings
      depend-on: 
       - py311_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py311/decrypt_masterkey_with_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_masterkey_with_js
      depend-on: 
       - py311_generate_decrypt_vectors_masterkey
      buildspec: codebuild/py311/decrypt_masterkey_with_js.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_generate_decrypt_vectors_keyrings
      buildspec: codebuild/py311/generate_decrypt_vectors_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_keyrings_with_masterkey
      depend-on: 
       - py311_generate_decrypt_vectors_keyrings
      buildspec: codebuild/py311/decrypt_keyrings_with_masterkey.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_keyrings_with_keyrings
      depend-on: 
       - py311_generate_decrypt_vectors_keyrings
      buildspec: codebuild/py311/decrypt_keyrings_with_keyrings.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: py311_decrypt_keyrings_with_js
      depend-on: 
       - py311_generate_decrypt_vectors_keyrings
      buildspec: codebuild/py311/decrypt_keyrings_with_js.yml
      env:
        image: aws/codebuild/standard:7.0

    # - identifier: py312_integ
    #   buildspec: codebuild/py312/integ.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_integ_mpl
    #   buildspec: codebuild/py312/integ_mpl.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_examples
    #   buildspec: codebuild/py312/examples.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_examples_mpl
    #   buildspec: codebuild/py312/examples_mpl.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_awses_latest
    #   buildspec: codebuild/py312/awses_local.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_awses_latest_mpl
    #   buildspec: codebuild/py312/awses_local_mpl.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_mplawses_latest_mpl
    #   buildspec: codebuild/py312/mplawses_local_mpl.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_decrypt_dafny_esdk_vectors_masterkey
    #   buildspec: codebuild/py312/decrypt_dafny_esdk_vectors_masterkey.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_decrypt_dafny_esdk_vectors_keyrings
    #   buildspec: codebuild/py312/decrypt_dafny_esdk_vectors_keyrings.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_decrypt_net_401_vectors_masterkey
    #   buildspec: codebuild/py312/decrypt_net_401_vectors_masterkey.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_decrypt_net_401_vectors_keyrings
    #   buildspec: codebuild/py312/decrypt_net_401_vectors_keyrings.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_generate_decrypt_vectors_masterkey
    #   buildspec: codebuild/py312/generate_decrypt_vectors_masterkey.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_decrypt_masterkey_with_masterkey
    #   depend-on: 
    #    - py312_generate_decrypt_vectors_masterkey
    #   buildspec: codebuild/py312/decrypt_masterkey_with_masterkey.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_decrypt_masterkey_with_keyrings
    #   depend-on: 
    #    - py312_generate_decrypt_vectors_masterkey
    #   buildspec: codebuild/py312/decrypt_masterkey_with_keyrings.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_decrypt_masterkey_with_js
    #   depend-on: 
    #    - py312_generate_decrypt_vectors_masterkey
    #   buildspec: codebuild/py312/decrypt_masterkey_with_js.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_generate_decrypt_vectors_keyrings
    #   buildspec: codebuild/py312/generate_decrypt_vectors_keyrings.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_decrypt_keyrings_with_masterkey
    #   depend-on: 
    #    - py312_generate_decrypt_vectors_keyrings
    #   buildspec: codebuild/py312/decrypt_keyrings_with_masterkey.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_decrypt_keyrings_with_keyrings
    #   depend-on: 
    #    - py312_generate_decrypt_vectors_keyrings
    #   buildspec: codebuild/py312/decrypt_keyrings_with_keyrings.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    # - identifier: py312_decrypt_keyrings_with_js
    #   depend-on: 
    #    - py312_generate_decrypt_vectors_keyrings
    #   buildspec: codebuild/py312/decrypt_keyrings_with_js.yml
    #   env:
    #     image: aws/codebuild/standard:7.0
    #
    # - identifier: code_coverage
    #   buildspec: codebuild/coverage/coverage.yml
    # - identifier: code_coverage_mpl
    #   buildspec: codebuild/coverage/coverage_mpl.yml
    #   env:
    #     image: aws/codebuild/standard:7.0

    # - identifier: compliance
    #   buildspec: codebuild/compliance/compliance.yml
