version: 0.2
phases:
  install:
    commands:
      - pip install "tox < 4.0"
  build:
    commands:
      - cd decrypt_oracle
      - tox -e chalice-deploy
artifacts:
  type: zip
  files:
    - decrypt_oracle/transformed.yaml
