# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
class AWSEncryptionSDKClientError(Exception): ...
class BadCiphertextError(AWSEncryptionSDKClientError): ...
class DecryptKeyError(AWSEncryptionSDKClientError): ...
class EncryptKeyError(AWSEncryptionSDKClientError): ...
class MasterKeyProviderError(AWSEncryptionSDKClientError): ...
class NotFoundError(AWSEncryptionSDKClientError): ...
class NotSupportedError(AWSEncryptionSDKClientError): ...
class SerializationError(AWSEncryptionSDKClientError): ...
class UnknownIdentityError(AWSEncryptionSDKClientError): ...
class ActionNotPermittedError(AWSEncryptionSDKClientError): ...
class InvalidAlgorithmError(AWSEncryptionSDKClientError): ...
class InvalidConfigError(AWSEncryptionSDKClientError): ...
class GenerateKeyError(AWSEncryptionSDKClientError): ...
class CustomKeyStoreError(AWSEncryptionSDKClientError): ...
class CacheError(AWSEncryptionSDKClientError): ...
class MaxConsecutiveSleepRoundsExceededError(AWSEncryptionSDKClientError): ...
