# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
from enum import Enum
from typing import Any, Dict, Optional, Tuple, Type, TypeVar

__version__: str
USER_AGENT_SUFFIX: str

class SerializationVersion(Enum):
    V1 = ...
    V2 = ...

class ObjectType(Enum):
    CUSTOMER_AE_DATA = ...

class ContentType(Enum):
    NO_FRAMING = ...
    FRAMED_DATA = ...

class ContentAADString(Enum):
    FRAME_STRING_ID = ...
    FINAL_FRAME_STRING_ID = ...
    NON_FRAMED_STRING_ID = ...

class CommitmentPolicy(Enum):
    FORBID_ENCRYPT_ALLOW_DECRYPT = ...
    REQUIRE_ENCRYPT_ALLOW_DECRYPT = ...
    REQUIRE_ENCRYPT_REQUIRE_DECRYPT = ...

class EncryptionType(Enum):
    SYMMETRIC = ...
    ASYMMETRIC = ...

class EncryptionKeyType(Enum):
    SYMMETRIC = ...
    RSA = ...

class EncryptionSuite(Enum):
    AES_128_GCM_IV12_TAG16 = ...
    AES_192_GCM_IV12_TAG16 = ...
    AES_256_GCM_IV12_TAG16 = ...
    algorithm: Any
    mode: Any
    data_key_length: int
    iv_length: int
    auth_length: int
    tag_len: int
    auth_key_length: int

class KDFSuite(Enum): ...
class AuthenticationSuite(Enum): ...

_T = TypeVar("_T", bound="AlgorithmSuite")

class AlgorithmSuite(Enum):
    AES_128_GCM_IV12_TAG16 = ...
    AES_192_GCM_IV12_TAG16 = ...
    AES_256_GCM_IV12_TAG16 = ...
    AES_128_GCM_IV12_TAG16_HKDF_SHA256 = ...
    AES_192_GCM_IV12_TAG16_HKDF_SHA256 = ...
    AES_256_GCM_IV12_TAG16_HKDF_SHA256 = ...
    AES_128_GCM_IV12_TAG16_HKDF_SHA256_ECDSA_P256 = ...
    AES_192_GCM_IV12_TAG16_HKDF_SHA384_ECDSA_P384 = ...
    AES_256_GCM_IV12_TAG16_HKDF_SHA384_ECDSA_P384 = ...
    AES_256_GCM_HKDF_SHA512_COMMIT_KEY = ...
    AES_256_GCM_HKDF_SHA512_COMMIT_KEY_ECDSA_P384 = ...

    algorithm_id: int
    encryption: Any
    message_format_version: SerializationVersion
    kdf: Any
    authentication: Any
    allowed: bool
    encryption_algorithm: Any
    encryption_mode: Any
    data_key_len: int
    iv_len: int
    auth_key_len: int
    auth_len: int
    kdf_type: Any
    kdf_hash_type: Any
    signing_algorithm_info: Any
    signing_hash_type: Any
    signature_len: int
    header_auth_iv: bytes

    @classmethod
    def get_by_id(cls: Type[_T], algorithm_id: int) -> _T: ...
    def id_as_bytes(self) -> bytes: ...
    def is_cacheable(self) -> bool: ...
    def is_committing(self) -> bool: ...
    def is_signing(self) -> bool: ...
    def algorithm_suite_data_length(self) -> int: ...

Algorithm = AlgorithmSuite

class WrappingAlgorithm(Enum):
    AES_128_GCM_IV12_TAG16_NO_PADDING = ...
    AES_192_GCM_IV12_TAG16_NO_PADDING = ...
    AES_256_GCM_IV12_TAG16_NO_PADDING = ...
    RSA_OAEP_SHA1_MGF1 = ...
    RSA_OAEP_SHA256_MGF1 = ...
    RSA_OAEP_SHA384_MGF1 = ...
    RSA_OAEP_SHA512_MGF1 = ...
    RSA_PKCS1 = ...

class SequenceIdentifier(Enum):
    SEQUENCE_NUMBER = ...
