name: AWS CodeBuild CI

on:
  pull_request:
  push:
  # Run once a day
  schedule:
    - cron: "0 0 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  codebuild-tests:
    name: AWS CodeBuild CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "38"
          - "39"
          - "310"
          - "311"
          - "312"
        codebuild_file_name:
          - "awses_local.yml"
          - "examples.yml"
          - "integ.yml"
      exclude:
        # No "awses_local.yml" file exists in py39/
        - python: "39"
          codebuild_file_name: "awses_local.yml"
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 3600
      - name: Run python-${{ matrix.python }} ${{ matrix.codebuild_file_name }}
        uses: aws-actions/aws-codebuild-run-build@v1
        timeout-minutes: 60
        with:
          project-name: python-esdk
          buildspec-override: codebuild/py${{ matrix.python }}/${{ matrix.codebuild_file_name }}
