version: 0.2

env:
  variables:
    BRANCH: "master"
  secrets-manager:
    TWINE_USERNAME: PyPiAdmin:username 
    TWINE_PASSWORD: PyPiAdmin:password

phases:
  install:
    commands:
      - pip install tox
      - pip install --upgrade pip
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - git checkout $BRANCH
      - CURRENT_COMMIT=$(git rev-parse --short HEAD)
      - |
        if expr "${CURRENT_COMMIT}" != ${COMMIT_ID}; then
          echo "HEAD of repository commit (${CURRENT_COMMIT}) did not match expected commit (${COMMIT_ID}), stopping"
          exit 1;
        fi
  build:
    commands:
      - tox -e park
      - tox -e release

batch:
  fast-fail: true 
  build-graph:
    - identifier: prod_release
    - identifier: validate_release
      depend-on:
        - prod_release
      buildspec: codebuild/release/validate.yml
      env:
        variables:
          PIP_INDEX_URL: https://pypi.python.org/simple/
