version: 0.2

env:
  secrets-manager:
    TWINE_USERNAME: PyPiAdmin:username 
    TWINE_PASSWORD: PyPiAdmin:password

phases:
  install:
    runtime-versions:
      python: latest
  build:
    commands:
      - pip install tox
      - git fetch origin $COMMIT_ID:$COMMIT_ID --depth=1
      - git checkout $COMMIT_ID
      - tox -e park
      - tox -e release
      - git clone https://github.com/aws-samples/busy-engineers-document-bucket.git
      - cd busy-engineers-document-bucket/exercises/python/encryption-context-complete
      - sed -i "s/aws_encryption_sdk/aws_encryption_sdk==$VERSION/" requirements-dev.txt
      - tox -e test


batch:
  fast-fail: false
  build-list:
    - identifier: prod_release
