version: 0.2

env:
  variables:
    BRANCH: "master"
  secrets-manager:
    TWINE_USERNAME: PyPiAdmin:username 
    TWINE_PASSWORD: PyPiAdmin:password

phases:
  install:
    runtime-versions:
      python: latest
  build:
    commands:
      - pip install tox
      - git checkout $BRANCH
      - tox -e park
      - tox -e release
      - git clone https://github.com/aws-samples/busy-engineers-document-bucket.git
      - cd busy-engineers-document-bucket/exercises/python/encryption-context-complete
      - tox -e test


batch:
  fast-fail: false
  build-list:
    - identifier: prod_release
