version: 0.2

env:
  variables:
    BRANCH: "master"
  secrets-manager:
    TWINE_USERNAME: PyPiAdmin:username 
    TWINE_PASSWORD: PyPiAdmin:password

phases:
  install:
    commands:
      - pip install tox
      - pip install --upgrade pip
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - git checkout $BRANCH
      - FOUND_VERSION=$(sed -n 's/__version__ = "\(.*\)"/\1/p' src/aws_encryption_sdk/identifiers.py)
      - |
        if expr ${FOUND_VERSION} != ${VERSION}; then
          echo "identifiers.py version (${FOUND_VERSION}) does not match expected version (${VERSION}), stopping"
          exit 1;
        fi
  build:
    commands:
      - tox -e park
      - tox -e release

batch:
  fast-fail: true 
  build-graph:
    - identifier: release_to_prod
    - identifier: validate_prod_release
      depend-on:
        - release_to_prod
      buildspec: codebuild/release/validate.yml
      env:
        variables:
          PIP_INDEX_URL: https://pypi.python.org/simple/
